### ISSUE TITLE
Render UGNT for downstream processing.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord-dev/ugnt-app#20]
As a Textual Critic, I want to render my UGNT for downstream processing.

- [x] Convert to individual chapter blocks (0)
- [ ] Insert variant symbols into text (1) Blocked by Todd
- [ ] Markup for html or md (2) Blocked by Todd
- [ ] Add decorations like book title and other doc info. (3) Blocked by Todd

**Comment by toddlprice** [comment]
Klappy has requested that we be able to output the UGNT as USFM.
