### ISSUE TITLE
Rearrange manuscripts on form

### ISSUE THREAD

**Issue by toddlprice** [unfoldingWord-dev/ugnt-app#8]
The Form sheet currently gives the data from WH, ST and Nestle. I need Nestle moved up above WH, and then the other "manuscripts" NA28, SBL, BYZ and KJTR listed between WH and ST.
![matt 1 screen shot greekcntr-org add mss](https://cloud.githubusercontent.com/assets/16920146/19922800/9ba14fe2-a0e4-11e6-818d-69fa1bc99b25.png)

## Notes

Bruce suggests that if the import script imports them in the correct order then the Google sheet will display them properly.

**Comment by toddlprice** [comment]
As a user, I want this app to list (probably in new rows 21-23 and maybe more) which Greek manuscripts contain the word I keep in the Results cell, which Greek manuscripts have no word there (a blank), and which Greek manuscripts contain a different word for that cell as well as what that word is. It is possible that there could be a need for several rows since conceivably a given cell might have a number of different words, so that the possibilities might be 1) word I retain in the cell, 2) blank 3) different word A, 4) different word B, 5) different word C.  It is possible that there could be more though this will be a rare occurrence. When it is time to show the apparatus, it should list each word choice followed by the Greek manuscripts that have that word.

**Comment by phillip-hopper** [comment]
@toddlprice We purposely excluded NA28, SBL, BYZ and KJTR because they are not public domain. Do we have permission to use them now?

**Comment by toddlprice** [comment]
BYZ, SBL and KJTR are Creative Commons so we can use them. You are correct that NA28 is copyrighted.
